version: "3.9"
services:
  server:
    image: "node:14-alpine3.15"
    entrypoint: ["npm", "run", "start"]
    volumes:
      - ./server:/server
    working_dir: "/server"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://0.0.0.0:3000/ping"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 2s

  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9091:3000"
    volumes:
      - ./grafana:/var/lib/grafana

  consumer-go:
    image: golang:latest
    volumes:
      - ./consumer-go:/consumer
    working_dir: /consumer
    depends_on:
      server:
        condition: service_healthy

    entrypoint: ["go", "run", "main.go"]
    environment:
      APP_URL: "http://server:3000/flip"

  consumer-rb:
    image: ruby:alpine3.16
    volumes:
      - ./consumer-rb:/consumer
    working_dir: /consumer
    depends_on:
      server:
        condition: service_healthy

    entrypoint: ["ruby", "consumer.rb"]
    environment:
      APP_URL: "http://server:3000/flip"
