version: "3.9"
networks:
  backend:
    internal: true
  public:
    internal: false

services:
  server:
    image: "node:14-alpine3.15"
    entrypoint: ["npm", "run", "start"]
    volumes:
      - ./server:/server
    working_dir: "/server"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://0.0.0.0:3000/ping"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 2s

  caddy:
    image: caddy:latest
    volumes:
      - ./caddy:/etc/caddy
    ports:
      - "8080:8080"
      - "2019:2019"

    networks:
      - backend
      - public

  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    networks:
      - backend
      - public
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9091:3000"
    networks:
      - backend
      - public
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards

  consumer-go:
    image: golang:latest
    volumes:
      - ./consumer-go:/consumer
    working_dir: /consumer
    networks:
      - backend
    depends_on:
      server:
        condition: service_healthy

    entrypoint: ["go", "run", "main.go"]
    environment:
      APP_URL: "http://caddy:8080/flip"

  consumer-rb:
    image: ruby:alpine3.16
    volumes:
      - ./consumer-rb:/consumer
    networks:
      - backend
    working_dir: /consumer
    depends_on:
      server:
        condition: service_healthy

    entrypoint: ["ruby", "consumer.rb"]
    environment:
      APP_URL: "http://caddy:8080/flip"
