global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "server"
    static_configs:
      - targets:
          - server:3000
  - job_name: "caddy"
    static_configs:
      - targets:
          - caddy:2019
